############################
# STEP 1 build executable binary
############################
FROM golang:1.24-alpine3.20 AS builder

# Install necessary build tools and SQLite headers
RUN apk update && apk add --no-cache \
  build-base \
  sqlite-dev \
  sqlite \
  gcc \
  musl-dev

# Enable CGO
ENV CGO_ENABLED=1
WORKDIR /app
COPY . .

# Fetch dependencies.
RUN go mod download
# Build the binary with optimizations
RUN go build -a -ldflags="-w -s" -o /app

#############################
## STEP 2 build a smaller image
#############################
FROM alpine:3.20
RUN apk add --no-cache ffmpeg
WORKDIR /app
# Copy compiled from builder.
COPY --from=builder /app /app
# Expose port 8080 to the outside world
EXPOSE 8080
# Run the binary.
ENTRYPOINT ["/app"]